package week1.four;

import java.util.Random;
import java.util.Scanner;

public class nameGenerator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        String[] firstNames = {"Aliana", "Motia", "Chani", "Diana", "Elizabeth", "Fiona", "Starlight", "Hannah"};
        String[] lastNames = {"Ali", "Ahmad", "Brown", "Wills", "Mali", "Forger", "Ruth", "Benz"};
        System.out.print("How many random names should be generated? ");
        int count = scanner.nextInt();

        // System, Just it has a Huge possibility of names duplication since it's randomly generated by times the user specifies.
        System.out.println("\nGenerated Names:");
        for (int i = 0; i < count; i++) {
            int firstIndex = random.nextInt(firstNames.length);
            int lastIndex = random.nextInt(lastNames.length);
            String fullName = firstNames[firstIndex] + " " + lastNames[lastIndex];
            System.out.println((i + 1) + ". " + fullName);
        }
    }
}